# Generated by Django 5.2.1 on 2025-05-14 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mood', models.CharField(choices=[('happy', 'Веселий'), ('sad', 'Сумний'), ('angry', 'Злий'), ('neutral', 'Нейтральний'), ('excited', 'Задоволений'), ('anxious', 'Тривожний')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запис про настрій',
                'verbose_name_plural': 'Записи про настрої',
            },
        ),
    ]
